-- Migration: Create homework videos table for student homework submissions

CREATE TABLE IF NOT EXISTS fc_homework_videos (
    id INT PRIMARY KEY AUTO_INCREMENT,
    uuid CHAR(36) NOT NULL UNIQUE,
    player_id INT NOT NULL,
    user_id INT NOT NULL,
    classroom_id INT NULL,
    title VARCHAR(255) NOT NULL,
    description TEXT NULL,
    video_path VARCHAR(500) NOT NULL,
    original_filename VARCHAR(255) NOT NULL,
    stored_filename VARCHAR(255) NOT NULL,
    mime_type VARCHAR(100),
    file_size INT,
    duration_seconds INT NULL COMMENT 'Video duration in seconds',
    status ENUM('submitted', 'reviewed', 'approved') DEFAULT 'submitted',
    coach_feedback TEXT NULL,
    coach_rating TINYINT NULL COMMENT 'Rating 1-5',
    reviewed_by INT NULL,
    reviewed_at TIMESTAMP NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    deleted_at TIMESTAMP NULL,
    FOREIGN KEY (player_id) REFERENCES fc_players(id) ON DELETE CASCADE ON UPDATE CASCADE,
    FOREIGN KEY (user_id) REFERENCES fc_users(id) ON DELETE CASCADE ON UPDATE CASCADE,
    FOREIGN KEY (classroom_id) REFERENCES fc_classrooms(id) ON DELETE SET NULL ON UPDATE CASCADE,
    FOREIGN KEY (reviewed_by) REFERENCES fc_users(id) ON DELETE SET NULL ON UPDATE CASCADE,
    INDEX idx_player_id (player_id),
    INDEX idx_user_id (user_id),
    INDEX idx_classroom_id (classroom_id),
    INDEX idx_status (status),
    INDEX idx_created_at (created_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
